---
title: "GBM"
author: "Yuning Pan"
date: "2023-05-09"
output: html_document
---

GBM model for comparison with the XGBoost model, only contains prediction information, did not include ALE in the GBM model
```{r}
library(readxl)
library("xlsx")
#cruciforms = read.xlsx("/projectnb/darpa/pyuning/frag modeling/Ensemble models/data_c.xlsx",1)
#fragments = read.xlsx("/projectnb/darpa/pyuning/frag modeling/Ensemble models/data_f.xlsx",1)
cruciforms <- readRDS("/projectnb/darpa/pyuning/frag modeling/Ensemble models/cruciforms.rds")
#fragments <- readRDS("/projectnb/darpa/pyuning/frag modeling/Ensemble models/fragments.rds")
fragments <- readRDS("/projectnb/darpa/pyuning/frag modeling/Ensemble models/Paper_Revision/fragments.rds")
```


```{r}
cruciforms$Solvent = as.numeric(as.factor(cruciforms$Solvent))
fragments$Solvent = as.numeric(as.factor(fragments$Solvent))
#cruciforms = cruciforms[,c('HOMO','EG','Lmax','KK','Solvent','Emission')]
#fragments = fragments[,c('A1HOMO','A1EG','A1Lmax','A1KK','A2HOMO','A2EG','A2Lmax','A2KK','Solvent','Emission')]
cruciforms = cruciforms[,c('HOMO','EG','Lmax','KK','Solvent','Emission')]
fragments = fragments[,c('2,6 HOMO','2,6 EG','2,6 Lmax','2,6 KK','4,8 HOMO','4,8 EG','4,8 Lmax','4,8 KK','Solvent','Emission')]

#data for cruciform model
data_c_variables <- as.matrix(cruciforms[1:81,-ncol(cruciforms)])
data_c_y <- cruciforms[1:81,"Emission"]
validate_c_variables <- as.matrix(cruciforms[82:89,-ncol(cruciforms)])
validate_c_y <- cruciforms[82:89,"Emission"]

#data for fragment model
data_f_variables <- as.matrix(fragments[1:81,-ncol(fragments)])
data_f_y <- fragments[1:81,"Emission"]
validate_f_variables <- as.matrix(fragments[82:89,-ncol(fragments)])
validate_f_y <- fragments[82:89,"Emission"]
```


```{r}
library("gbm")  # the main algorithm
library("caret")    # for the confusionmatrix() function (also needs e1071 package)
library(MLmetrics)

#Model & CV Settings
#grid_tune <-  expand.grid(interaction.depth = c(2, 4, 6), 
#                        n.trees = c(50,75,100), 
#                        shrinkage = c(0.025,0.05,0.1,0.3),
#                        n.minobsinnode = 1,
#                        bag.fraction = 0.7,
#                        train.fraction = 0.7)

grid_tune <-  expand.grid(interaction.depth = c(2, 4, 6), 
                        n.trees = c(500,750,1000), 
                        shrinkage = c(0.025,0.05,0.1,0.3),
                        n.minobsinnode = 1)
                        #bag.fraction = 0.7,
                        #train.fraction = 0.7)

train_control <- trainControl(method = "cv",
                              number=9,
                              verboseIter = FALSE,
                              allowParallel = TRUE)

#Cruciform model
GBM_C <- function(folds = 10, seeds = 2023){
  set.seed(seeds);index = sample(length(data_c_y), size = length(data_c_y)/folds)
  train_c_data <- data_c_variables[-index,]
  test_c_data <- data_c_variables[index,]
  train_c_y <- data_c_y[-index]
  test_c_y <- data_c_y[index]
  set.seed(2023);gbm_tune <- caret::train(x = train_c_data, y = train_c_y, trControl = train_control, tuneGrid = grid_tune, method= "gbm", verbose = FALSE)
  gbm.pred <- predict(gbm_tune, test_c_data)
  gbm.rmse = caret::RMSE(test_c_y, gbm.pred)   #1
  validate.pred <- predict(gbm_tune, validate_c_variables) #2
  gbm.mae = MLmetrics::MAE(test_c_y, gbm.pred) #3
  gbm.mse = MLmetrics::MSE(test_c_y, gbm.pred) #4
  gbm.mape = MLmetrics::MAPE(test_c_y, gbm.pred) #5
  return(list(gbm_tune, gbm.rmse, validate.pred, gbm.mae, gbm.mse, gbm.mape))
}

#Fragment model
GBM_F <- function(folds = 10, seeds = 2023){
  set.seed(seeds);index = sample(length(data_f_y), size = length(data_f_y)/folds)
  train_f_data <- data_f_variables[-index,]
  test_f_data <- data_f_variables[index,]
  train_f_y <- data_f_y[-index]
  test_f_y <- data_f_y[index]
  set.seed(2023);gbm_tune <- caret::train(x = train_f_data, y = train_f_y, trControl = train_control, tuneGrid = grid_tune, method= "gbm", verbose = FALSE)
  gbm.pred <- predict(gbm_tune, test_f_data)
  gbm.rmse = caret::RMSE(test_f_y, gbm.pred)   #1
  validate.pred <- predict(gbm_tune, validate_f_variables) #2
  gbm.mae = MLmetrics::MAE(test_f_y, gbm.pred) #3
  gbm.mse = MLmetrics::MSE(test_f_y, gbm.pred) #4
  gbm.mape = MLmetrics::MAPE(test_f_y, gbm.pred) #5
  return(list(gbm_tune, gbm.rmse, validate.pred, gbm.mae, gbm.mse, gbm.mape))
}
```


```{r}
list.of.packages <- c(
  "foreach",
  "doParallel",
  "ranger",
  "palmerpenguins",
  "tidyverse",
  "kableExtra"
  )

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]

if(length(new.packages) > 0){
  install.packages(new.packages, dep=TRUE)
}

#loading packages
for(package.i in list.of.packages){
  suppressPackageStartupMessages(
    library(
      package.i, 
      character.only = TRUE
      )
    )
}
library(foreach)
parallel::detectCores()
n.cores <- parallel::detectCores() - 1
my.cluster <- parallel::makeCluster(
  n.cores, 
  type = "PSOCK"
  )
print(my.cluster)
doParallel::registerDoParallel(cl = my.cluster) #register it to be used by %dopar%
foreach::getDoParRegistered() #check if it is registered
foreach::getDoParWorkers()  #how many workers are available
```

```{r}
iterations = 100

GBM_results_c <- foreach(i=1:iterations, .combine = 'cbind') %dopar%
  {
    GBM_C(folds = 10, seeds = i)
  }

GBM_results_f <- foreach(i=1:iterations, .combine = 'cbind') %dopar%
  {
    GBM_F(folds = 10, seeds = i)
  }
stopCluster(my.cluster)
```


```{r}
#setwd("/projectnb/darpa/pyuning/frag modeling/Ensemble models/Models Comparison")
setwd("/projectnb/darpa/pyuning/frag modeling/Ensemble models/Paper_Revision")
saveRDS(GBM_results_c, "GBM_results_c.rds")
saveRDS(GBM_results_f, "GBM_results_f.rds")
```

```{r}
#GBM_results_c <- readRDS("/projectnb/darpa/pyuning/frag modeling/Ensemble models/Models Comparison/GBM_results_c.rds")
#GBM_results_f <- readRDS("/projectnb/darpa/pyuning/frag modeling/Ensemble models/Models Comparison/GBM_results_f.rds")
GBM_results_c <- readRDS("/projectnb/darpa/pyuning/frag modeling/Ensemble models/Paper_Revision/GBM_results_c.rds")
GBM_results_f <- readRDS("/projectnb/darpa/pyuning/frag modeling/Ensemble models/Paper_Revision/GBM_results_f.rds")
```

some simple analysis
```{r}
validate.pred_c = matrix(unlist(GBM_results_c[3,]),ncol=8,byrow = TRUE)
validate.pred_f = matrix(unlist(GBM_results_f[3,]),ncol=8,byrow = TRUE)
validate.pred_c = apply(validate.pred_c, 2, mean) # prediction of the cruciform model on the holdout data
validate.pred_f = apply(validate.pred_f, 2, mean) # prediction of the fragment model on the holdout data
caret::RMSE(validate_c_y, validate.pred_c) # RMSE of the prediction of the cruciform model
caret::RMSE(validate_f_y, validate.pred_f) # RMSE of the prediction of the fragment model
MAE(validate_c_y, validate.pred_c) # MAE of the prediction of the cruciform model
MAE(validate_f_y, validate.pred_f) # MAE of the prediction of the fragment model
MSE(validate_c_y, validate.pred_c) # MSE of the prediction of the cruciform model
MSE(validate_f_y, validate.pred_f) # MSE of the prediction of the fragment model
MAPE(validate_c_y, validate.pred_c) # MAPE of the prediction of the cruciform model
MAPE(validate_f_y, validate.pred_f) # MAPE of the prediction of the fragment model


mean(unlist(GBM_results_c[2,])) # aveRMSE of the cruciform model on the testing sets
sd(unlist(GBM_results_c[2,])) # standard deviation of RMSE of the prediction of the cruciform model on the testing sets
mean(unlist(GBM_results_c[4,])) # aveMAE of the cruciform model on the testing sets
sd(unlist(GBM_results_c[4,])) # standard deviation of MAE of the prediction of the cruciform model on the testing sets
mean(unlist(GBM_results_c[5,])) # aveMSE of the cruciform model on the testing sets
sd(unlist(GBM_results_c[5,])) # standard deviation of MSE of the prediction of the cruciform model on the testing sets
mean(unlist(GBM_results_c[6,])) # aveMAPE of the cruciform model on the testing sets
sd(unlist(GBM_results_c[6,])) # standard deviation of MAPE of the prediction of the cruciform model on the testing sets
mean(unlist(GBM_results_f[2,])) # aveRMSE of the fragment model on the testing sets
sd(unlist(GBM_results_f[2,])) # standard deviation of RMSE of the prediction of the fragment model on the testing sets
mean(unlist(GBM_results_f[4,])) # aveMAE of the fragment model on the testing sets
sd(unlist(GBM_results_f[4,])) # standard deviation of MAE of the prediction of the fragment model on the testing sets
mean(unlist(GBM_results_f[5,])) # aveMSE of the fragment model on the testing sets
sd(unlist(GBM_results_f[5,])) # standard deviation of MSE of the prediction of the fragment model on the testing sets
mean(unlist(GBM_results_f[6,])) # aveMAPE of the fragment model on the testing sets
sd(unlist(GBM_results_f[6,])) # standard deviation of MAPE of the prediction of the fragment model on the testing sets
```